<?php

function moonrock_sample_display_menu() {
  $items = array();
  $items['moonrock_sample_display/search'] = array(
      'page callback' => 'moonrock_sample_display_search',
      'access callback' => 'moonrock_sample_display_search_access',
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function moonrock_sample_display_search_access() {
  return true;
}

function moonrock_sample_display_search() {

  $location = $_REQUEST['location'];
  $nid = $_REQUEST['nid'];

  $query = "SELECT {node}.title, {node}.nid, "
          . "{moonrock_sample}.vm, {moonrock_sample}.snapshot, {moonrock_sample}.location "
          . "FROM {node} "
          . "LEFT JOIN {moonrock_sample} ON moonrock_sample.nid = node.nid "
          . "WHERE node.type = 'moonrock_sample' ";

  $parameters = array();
  if ($location && strlen($location) > 0) {
    $query .= "AND {moonrock_sample}.location LIKE '%%%s%%' ";
    $parameters[] = $location;
  }

  if ($nid && strlen($nid) > 0) {
    $query .= "AND {node}.nid = %d ";
    $parameters[] = $nid;
  }

  $result = db_query($query, $parameters);
  $samples = array();
  while ($object = db_fetch_object($result)) {
    $samples[] = array(
        "id" => check_plain("node_{$object->nid}"),
        "title" => check_plain($object->title),
        "vm" => check_url($object->vm),
        "snapshot" => check_url($object->snapshot),
        "location" => check_plain($object->location),
    );
  }

  drupal_json(array(
      'status' => true,
      'data' => $samples,
  ));
}

function moonrock_sample_display_table_and_search($samples, $search = FALSE, $selection_name = NULL) {
  if ($selection_name)
    drupal_add_js(drupal_get_path('module', 'moonrock_sample_display') . '/js/moonrockSampleSelect.js');

  if ($search)
    drupal_add_js(drupal_get_path('module', 'moonrock_sample_display') . '/js/moonrockSampleSearch.js');

  drupal_add_js(drupal_get_path('module', 'moonrock_sample_display') . '/js/moonrockSampleDialog.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_sample_display') . '/js/init.js');

  drupal_add_css(drupal_get_path('module', 'moonrock_sample_display') . '/css/moonrock_sample.css');

  jquery_ui_add("ui.dialog");
  jquery_ui_add("ui.resizable");
  jquery_ui_add("ui.draggable");
  drupal_add_css(drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/jquery-ui.css');
  drupal_add_css(drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/ui.dialog.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_sample_display') . '/js/extend-dialog/jquery.dialogextend.js');
  
  $output = moonrock_sample_display_table($samples, $selection_name);
  if ($search) {
    $output .= moonrock_sample_display_create_search($samples, $selection_name);
  }
  return $output;
}

function moonrock_sample_display_create_search($samples, $selection_name = NULL) {
  drupal_add_css(drupal_get_path('module', 'moonrock_sample_display') . '/collapsible/diQuery-collapsiblePanel.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_sample_display') . '/collapsible/diQuery-collapsiblePanel.js');

  $output = '<div class="collapsibleContainer" title="' . t("Search") . '">';
  $output .= '<table class="moonrockSampleSearchFormTable">';
  $output .= '<tr><th width="200px;">Location</th><th></th></tr>';
  $output .= '<tr>';
  $output .= '<td><input name="location" id="moonrock_sample_search_location" type="text"></input></td>';
  $output .= '<td id="moonrock_sample_search_throbber"><div class="ahah-progress ahah-progress-throbber"><div>&nbsp;</div></div></td>';
  $output .= '</tr>';
  $output .= '</table>';
  $output .= '<div id="moonrock_sample_search_results"></div>';
  $output .= '</div>';

  return $output;
}

function moonrock_sample_display_table($samples, $selection_name = NULL) {
  drupal_add_css(drupal_get_path('module', 'moonrock_sample_display') . '/css/moonrock_sample.css');
  drupal_add_css(drupal_get_path('module', 'moonrock_sample_display') . '/css/moonrock_dialog.css');

  $output = '';
  foreach ($samples as $sample) {
    $output .= moonrock_sample_display_sample($sample, $selection_name);
  }

  return $output;
}

function moonrock_sample_display_sample($sample, $selection_name = NULL) {
  $option_id = "node_{$sample->nid}";
  $name_attr = $selection_name ? "name='$selection_name'" : "";

  $output = '';
  $output .= "<div class='moonrocksample' sample='{$option_id}'>";
  $output .= "  <div class='moonrocksampleimagecontainer'>";
  $output .= "    <img class='moonrocksampleimage' src='{$sample->snapshot}' sample='$option_id' $name_attr></img>";
  $output .= "  </div>";

  $output .= "  <div>";
  $output .= "    <center>";
  if ($selection_name) {
    $id = "{$selection_name}-node_{$sample->nid}";
    $output .= "      <input $name_attr id='$id' type='radio' value='$option_id'/>";
    $output .= "      <label class='option' for='$id'><b>{$sample->title}</b></label>";
  } else {
    $output .= "      <b>{$sample->title}</b>";
  }

  $output .= "    </center>";
  $output .= "  </div>";
  $output .= "</div>";


  $output .= "<div class='moonrocksampledialog' sample='$option_id'>";
  $output .= "<div class='moonrocksampleiframetopcontainer'>";
  $output .= "<div class='moonrocksampleiframecontainer'>";
  $output .= "<iframe class='moonrocksampleiframe' src='{$sample->vm}'></iframe>";
  $output .= "</div>";
  $output .= "</div>";
  $output .= "</div>";


  return $output;
}
