<?php

// $Id: pi_wiki_notes.module,v 1.2 2009/06/11 09:55:10 ou_mbg Exp $

/**
 * @file
 * Module for creating "pi_wiki_notes" node type
 */

/**
 * Implementation of hook_node_info().
 */
function moonrock_seesamples_node_info() {

  return array(
      'moonrock_seesamples' => array(
          'name' => t('Moonrock see samples'), // Required.
          'module' => 'moonrock_seesamples', // Required.
          'description' => t('See Moon rock samples'), // Required.
          'has_title' => TRUE,
          'title_label' => t('Title'),
          'has_body' => TRUE,
          'body_label' => t('Body'),
          'locked' => TRUE)
  );
}

/**
 * Implementation of hook_perm().
 */
function moonrock_seesamples_perm() {
  
}

/**
 * Implementation of hook_access().
 */
function moonrock_seesamples_access($op, $node, $account) {
  global $user;
  $details = get_inquiry_details_from_current_path();

  if ($op == 'create') {
    return check_node_function_of_activity($details->inquiry_id, $details->activity_id, $user->uid, 'add');
  }

  if ($op == 'update' || $op == 'delete') {
    return check_node_function_of_activity($details->inquiry_id, $details->activity_id, $user->uid, 'edit');
  }
}

/**
 * Implementation of hook_form().
 */
function moonrock_seesamples_form(&$node) {

  // Get metadata for this node type
  // (we use it for labeling title and body fields).
  // We defined this in pi_wiki_notes_node_info().
  $type = node_get_types('type', $node);
  global $user;

  $node_details = get_inquiry_details_from_current_path();
  if (is_numeric($node_details->activity_id)) {
    $current_activity = load_activity($node_details->activity_id);
  }

  if ($current_activity->name) {
    drupal_set_title(t($current_activity->name));
  }

  $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#required' => FALSE,
      '#default_value' => $node->title,
      '#weight' => -5
  );
  $form['body'] = array(
      '#type' => 'textarea',
      '#title' => t('Type the introduction to this activity'),
      '#required' => TRUE,
      '#default_value' => $node->body,
      '#weight' => -5
  );

  $form['body_filter']['samples'] = array(
      '#type' => 'textarea',
      '#title' => t('Samples'),
      '#required' => TRUE,
      '#default_value' => $node->samples,
      '#description' => t('Type the URLs of the samples and click the Save button when you are finished'),
      '#resizable' => TRUE,
      '#rows' => 8,
      '#cols' => 40,
      '#weight' => -2
  );

  $prefix = "";
  if ($current_activity->description) {
    $prefix .= "<p>" . check_plain($current_activity->description) . "</p>";
  }

  $form['#prefix'] = $prefix;

  return $form;
}

/**
 * Implementation of hook_insert().
 */
function moonrock_seesamples_insert($node) {
  db_query("INSERT INTO {moonrock_seesamples} (nid, vid, samples) VALUES ('%d', '%d', '%s')", $node->nid, $node->vid, $node->samples);
}

/**
 * Implementation of hook_update().
 */
function moonrock_seesamples_update($node) {
  if ($node->revision) {
    moonrock_seesamples_insert($node);
  } else {
    db_query("UPDATE {moonrock_seesamples} SET samples = '%s' WHERE vid = %d", $node->samples, $node->vid);
  }
}

/**
 * Implementation of hook_delete().
 */
function moonrock_seesamples_delete(&$node) {
  // Delete the related information we were saving for this node.
  db_query('DELETE FROM {moonrock_seesamples} WHERE nid = %d', $node->nid);
}

/**
 * Implementation of hook_load().
 */
function moonrock_seesamples_load($node) {
  return db_fetch_object(db_query('SELECT * FROM {moonrock_seesamples} WHERE vid = %d', $node->vid));
}

function moonrock_seesamples_link_alter(&$links, $node) {
  // remove attachment links from upload.module
  unset($links['upload_attachments']);
}

/**
 * Implementation of hook_view().
 */
function moonrock_seesamples_view($node, $teaser = FALSE, $page = FALSE) {
  // Use Drupal's default node view.
  $original_body = $node->body;
  $node = node_prepare($node, $teaser);

  $node->content['moonrock_seesamples'] = array(
      '#value' => theme('moonrock_seesamples', $node, $teaser),
      '#weight' => 2
  );
  
  if (!$teaser) {
    $node->content['body']['#value'] = '<div id="moonrock-activity-description">' . $original_body. '</div>';
  }
  
  return $node;
}

/**
 * MISSING
 *
 * @return multitype:multitype:multitype:string
 */
function moonrock_seesamples_theme() {
  return array(
      'moonrock_seesamples' => array(
          'arguments' => array('node', 'teaser'),
      ),
  );
}

/**
 * MISSING
 *
 * @param unknown_type $node
 * @return string
 */
function theme_moonrock_seesamples($node, $teaser) {
  //$output = $node->body;
  if (!$teaser) {
    module_load_include('inc', 'moonrock_seesamples', 'moonrock_seesamples.table');
    $output .= moonrock_data_form_seesamples_activity();
  }
  return $output;
}

