<?php

function moonrock_vm_view_theme() {
  return array(
      'moonrock_vm_view_vm_top_navigator' => array(
          'arguments' => array(),
      ),
      'moonrock_vm_view_vm' => array(
          'arguments' => array(),
      ),
      'moonrock_vm_view_vm_simple_page' => array(
          'arguments' => array(),
      ),
  );
}

function theme_moonrock_vm_view_vm_top_navigator() {
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vm_navigator.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/navigator.js');

  $output = ' <div id="moonrock-vm-navigator" class="moonrock-vm-navigator">'
          . '  <div id="moonrock-vm-navigator-previous" class="moonrock-vm-navigator-button moonrock-vm-navigator-previous"></div>'
          . '  <div class="moonrock-vm-navigator-prefix">' . t('Browsing ') . '</div>'
          . '  <div id="moonrock-vm-navigator-sample" class="moonrock-vm-navigator-sample"></div>'
          . '  <div id="moonrock-vm-navigator-next" class="moonrock-vm-navigator-button moonrock-vm-navigator-next"></div>'
          . ' </div>';
  return $output;
}

function theme_moonrock_vm_view_vm() {
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vm_view.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/vm.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/vmComm.js');
  moonrock_vm_state_load_resources();

  $output = '<div id="moonrock-vm-container" class="moonrock-vm-container">'
          . '  <div id="moonrock-vm-iframe-container" class="moonrock-vm-iframe-container">'
          . '    <iframe id="moonrock-vm-iframe" src="about:black"></iframe>'
          . '  </div>'
          . '  <div id="moonrock-vm-resize-container" class="moonrock-vm-resize-container">'
          . '    <canvas id="moonrock-vm-resize-canvas"></canvas>'
          . '  </div>'
          . '</div>';


  return $output;
}

function theme_moonrock_vm_view_vm_simple_page() {
  //$navigator = theme('moonrock_vm_view_vm_top_navigator');
  $vm = theme('moonrock_vm_view_vm');

//  return theme('moonrock_layout_vertical', array($navigator, $vm), array(false, TRUE), TRUE);
  return theme('moonrock_layout_vertical', array(
              array('content' => $vm, 'flex' => TRUE),
                  ), TRUE);
}

