<?php

function moonrock_vm_view_theme() {
  return array(
      'moonrock_vm_view_vm_top_navigator' => array(
          'arguments' => array(),
      ),
      'moonrock_vm_view_vm' => array(
          'arguments' => array(),
      ),
      'moonrock_vm_view_vm_simple_page' => array(
          'arguments' => array(),
      ),
  );
}

/*
  function theme_moonrock_vm_view_page($node, $vm_view = FALSE) {
  moonrock_vm_view_load_resources();

  $output = '';
  $output .= '<div id="moonrock-samples-pages" class="moonrock-samples-vm-page">';


  $output .= '<div id="moonrock-samples-page-browse" class="moonrock-samples-page moonrock-samples-page-hidden moonrock-samples-page-browse">';
  $output .= theme('moonrock_seesamples_table', $node, FALSE, TRUE);
  $output .= '</div>';

  $output .= '<div id="moonrock-samples-page-vm-top" class="moonrock-samples-page moonrock-samples-page-hidden moonrock-samples-page-vm-top">';
  $output .= '<div id="moonrock-samples-page-vm-top-expand" class="moonrock-samples-page-vm-top-sizemode moonrock-samples-page-vm-top-expand"><div class="icon"></div>' . t('Expand') . '</div>';
  $output .= '<div id="moonrock-samples-page-vm-top-restore" class="moonrock-samples-page-vm-top-sizemode moonrock-samples-page-vm-top-restore"><div class="icon"></div>' . t('Restore') . '</div>';
  $output .= $vm_view ? $vm_view : theme('moonrock_vm_view_vm');
  $output .= '</div>';

  $output .= '</div>';

  return $output;
  }

  function __theme_moonrock_vm_view_vm() {
  $output = '<div id="moonrock-samples-page-vm" class="moonrock-samples-page-vm">'
  . ' <div id="moonrock-samples-page-vm-sample" class="moonrock-samples-page-vm-sample">'
  . '  <div id="moonrock-samples-page-vm-sample-previous" class="moonrock-samples-page-vm-sample-button moonrock-samples-page-vm-sample-previous"></div>'
  . '  <div class="moonrock-samples-page-vm-sample-title">' . t('Browsing ') . '</div>'
  . '  <div id="moonrock-samples-page-vm-sample-title" class="moonrock-samples-page-vm-sample-title"></div>'
  . '  <div id="moonrock-samples-page-vm-sample-next" class="moonrock-samples-page-vm-sample-button moonrock-samples-page-vm-sample-next"></div>'
  . ' </div>'
  . ' <div id="moonrock-samples-page-vm-iframe-container" class="moonrock-samples-page-vm-iframe-container"></div>'
  . ' <div id="moonrock-samples-page-vm-resize" class="moonrock-samples-page-vm-resize"><canvas id="moonrock-samples-page-vm-resize-canvas"></canvas></div>'
  . '</div>';


  return $output;
  }

  function moonrock_vm_view_load_resources() {
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vmMeasureField.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/jquery.vmMeasureField.js');

  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/vmComm.js');
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vm_view.css');
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vm_browse.css');

  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/expand.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/history.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/vmManagement.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/jquery.ba-bbq.js');
  }

 */

function theme_moonrock_vm_view_vm_top_navigator() {
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vm_navigator.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/navigator.js');

  $output = ' <div id="moonrock-vm-navigator" class="moonrock-vm-navigator">'
          . '  <div id="moonrock-vm-navigator-previous" class="moonrock-vm-navigator-button moonrock-vm-navigator-previous"></div>'
          . '  <div class="moonrock-vm-navigator-prefix">' . t('Browsing ') . '</div>'
          . '  <div id="moonrock-vm-navigator-sample" class="moonrock-vm-navigator-sample"></div>'
          . '  <div id="moonrock-vm-navigator-next" class="moonrock-vm-navigator-button moonrock-vm-navigator-next"></div>'
          . ' </div>';
  return $output;
}

function theme_moonrock_vm_view_vm() {
  drupal_add_css(drupal_get_path('module', 'moonrock_vm_view') . '/css/vm_view.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/vm.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_vm_view') . '/js/vmComm.js');
  moonrock_vm_state_load_resources();
  
  $output = '<div id="moonrock-vm-container" class="moonrock-vm-container">'
          . '  <div id="moonrock-vm-iframe-container" class="moonrock-vm-iframe-container">'
          . '    <iframe id="moonrock-vm-iframe" src="about:black"></iframe>'
          . '  </div>'
          . '  <div id="moonrock-vm-resize-container" class="moonrock-vm-resize-container">'
          . '    <canvas id="moonrock-vm-resize-canvas"></canvas>'
          . '  </div>'
          . '</div>';
          

  return $output;
}

function theme_moonrock_vm_view_vm_simple_page() {
  $navigator = theme('moonrock_vm_view_vm_top_navigator');
  $vm = theme('moonrock_vm_view_vm');

  return theme('moonrock_layout_vertical', array($navigator, $vm), array(false, TRUE), TRUE);
//  return theme('moonrock_layout_vertical', array('a', $vm), array(FALSE, TRUE), TRUE);
}

