<?php

function moonrock_sample_ajax_menu() {
  $items = array();

  $items['moonrock_sample_ajax/samplesearch'] = array(
      'page callback' => 'moonrock_sample_ajax_samplesearch',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  $items['activity/%/samplesearch'] = array(
      'page callback' => 'moonrock_sample_ajax_samplesearch',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );

  $items['moonrock_sample_ajax/snapshotsearch'] = array(
      'page callback' => 'moonrock_sample_ajax_snapshotsearch',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  $items['activity/%/snapshotsearch'] = array(
      'page callback' => 'moonrock_sample_ajax_snapshotsearch',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );

  $items['moonrock_sample_ajax/sample_dialog'] = array(
      'page callback' => 'moonrock_sample_ajax_sample_dialog',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  $items['activity/%/sample_dialog'] = array(
      'page callback' => 'moonrock_sample_ajax_sample_dialog',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );

  $items['moonrock_sample_ajax/newsnapshot/submit'] = array(
      'page callback' => 'moonrock_sample_ajax_newsnapshot_submit',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function moonrock_sample_ajax_access() {
  return TRUE;
}

function _moonrock_sample_ajax_search_getparam($name, $type = NULL, $param = NULL) {
  if (!isset($_REQUEST[$name])) {
    return FALSE;
  } else {
    $value = $_REQUEST[$name];
    if (is_array($value)) {
      return count($value) > 0 ? $value : FALSE;
    } else {
      if (strlen($value) == 0) {
        return FALSE;
      } else if ($type == 'int') {
        return intval($value);
      } else if ($type == 'array') {
        return explode($param, $value);
      } else {
        return $value;
      }
    }
  }
}

function moonrock_sample_ajax_sample_dialog() {
  $nid = isset($_REQUEST['nid']) ? $_REQUEST['nid'] : 0;
  $snapshooting = isset($_REQUEST['snapshooting']) ? $_REQUEST['snapshooting'] === 'true' : FALSE;
  echo moonrock_sample_utils_create_sample_dialog($nid, $snapshooting);
}

function moonrock_sample_ajax_samplesearch() {
  $nid = _moonrock_sample_ajax_search_getparam('nid');

  if (!$nid) {
    $location = _moonrock_sample_ajax_search_getparam('location');
  }

  $nids = array();
  if ($nid) {
    $nids[] = $nid;
  } else {
    $query = "SELECT {node}.nid FROM {moonrock_sample} "
            . "LEFT JOIN {node} ON moonrock_sample.nid = node.nid ";
    $condition = "WHERE {node}.type = 'moonrock_sample' ";

    $parameters = array();

    if ($location) {
      $condition .= "AND {moonrock_sample}.location LIKE '%%%s%%' ";
      $parameters[] = $location;
    }

    $result = db_query($query . $condition, $parameters);

    while ($object = db_fetch_object($result)) {
      $nids[] = $object->nid;
    }
  }

  $samples = array();
  foreach ($nids as $nid) {
    $samples[] = moonrock_sample_utils_prepare_sample_object($nid);
  }

  $result = array(
      "status" => TRUE,
      "items" => $samples,
  );
  drupal_json($result);
}

function moonrock_sample_ajax_snapshotsearch() {
  $nid = _moonrock_sample_ajax_search_getparam('nid');

  if (!$nid) {
    $usesamplerefs = _moonrock_sample_ajax_search_getparam('usesamplerefs', 'int');
    if ($usesamplerefs) {
      $samplerefs = _moonrock_sample_ajax_search_getparam('samplerefs', 'array', ' ');
    }
    $author = _moonrock_sample_ajax_search_getparam('author');
    $keyword = _moonrock_sample_ajax_search_getparam('keyword');
  }

  $nids = array();
  if ($nid) {
    $nids[] = $nid;
  } else {
    $query = "SELECT {node}.nid FROM {moonrock_snapshot} "
            . "LEFT JOIN {node} ON {moonrock_snapshot}.nid = {node}.nid ";
    $condition = "WHERE {node}.type = 'moonrock_snapshot' ";

    $parameters = array();

    if ($samplerefs) {
      $condition .= "AND {moonrock_snapshot}.sample_ref IN (" . db_placeholders($samplerefs, "int") . ") ";
      $parameters = array_merge($parameters, $samplerefs);
    }

    if ($author === "me") {
      global $user;
      $condition .= "AND {node}.uid=%d ";
      $parameters[] = $user->uid;
    }

    if ($keyword) {
      $condition .= "AND {moonrock_snapshot}.notes LIKE '%%%s%%' ";
      $parameters[] = $keyword;
    }

    $result = db_query($query . $condition, $parameters);

    while ($object = db_fetch_object($result)) {
      $nids[] = $object->nid;
    }
  }

  foreach ($nids as $nid) {
    $snapshots[] = moonrock_sample_utils_prepare_snapshot_object($nid);
  }

  $result = array(
      "status" => TRUE,
      "items" => $snapshots,
  );
  drupal_json($result);
}

function moonrock_sample_ajax_newsnapshot_submit() {
  $form_state = array();
  module_load_include('inc', 'node', 'node.pages');
  $node = new stdClass();
  $node->type = 'moonrock_snapshot';

  $form_state['values']['title'] = $_POST['title'];
  $form_state['values']['notes'] = $_POST['notes'];
  $form_state['values']['vm_parameters'] = $_POST['vm_parameters'];
  $form_state['values']['sample_ref'] = $_POST['sample_ref'];

  drupal_execute('story_node_form', $form_state, $node);
  $errors = form_get_errors();

  if ($errors) {
    $output = '<div class="messages error"><ul>';
    foreach ($errors as $message) {
      $output .= "<li>$message</li>";
    }
    $output .= '</ul></div>';
    $result = array("status" => FALSE, "data" => $output);
  } else {
    $node->title = $_POST['title'];
    $node->notes = $_POST['notes'];
    $node->vm_parameters = $_POST['vm_parameters'];
    $node->sample_ref = $_POST['sample_ref'];
    node_save($node);

    $result = array(
        "status" => TRUE,
        "snapshot" => array(
            "nid" => $node->nid,
            "title" => $node->title,
        ),
    );
  }
  unset($_SESSION['messages']); // same as above
  drupal_json($result);
}

