<?php

function moonrock_sample_ajax_menu() {
  $items = array();
  $items['moonrock_sample_ajax/search'] = array(
      'page callback' => 'moonrock_sample_ajax_search',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  $items['activity/%/sample_search'] = array(
      'page callback' => 'moonrock_sample_ajax_search',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );


  $items['moonrock_sample_ajax/sample_dialog'] = array(
      'page callback' => 'moonrock_sample_ajax_sample_dialog',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  $items['activity/%/sample_dialog'] = array(
      'page callback' => 'moonrock_sample_ajax_sample_dialog',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );

  $items['moonrock_sample_ajax/newsnapshot/submit'] = array(
      'page callback' => 'moonrock_sample_ajax_newsnapshot_submit',
      'access callback' => 'moonrock_sample_ajax_access',
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function moonrock_sample_ajax_access() {
  return TRUE;
}

function _moonrock_sample_ajax_search_getparam($name) {
  if (!isset($_REQUEST[$name])) {
    return FALSE;
  } else {
    $value = $_REQUEST[$name];
    if (is_array($value)) {
      return count($value) > 0 ? $value : FALSE;
    } else {
      return strlen($value) > 0 ? $value : FALSE;
    }
  }
}

function moonrock_sample_ajax_sample_dialog() {
  $nid = isset($_REQUEST['nid']) ? $_REQUEST['nid'] : 0;
  echo moonrock_sample_utils_create_sample_dialog($nid);
}

function moonrock_sample_ajax_search() {
  $nid = _moonrock_sample_ajax_search_getparam('nid');

  if (!$nid) {
    $samples_any = _moonrock_sample_ajax_search_getparam('samples_any');
    $main_samples = $samples_any ? FALSE : _moonrock_sample_ajax_search_getparam('main_samples');
    $location = _moonrock_sample_ajax_search_getparam('location');
    $username = _moonrock_sample_ajax_search_getparam('username');
    $keyword = _moonrock_sample_ajax_search_getparam('keyword');
  }

  $select_mode = _moonrock_sample_ajax_search_getparam('select_mode');

  $samples = array();
  if ($nid || $samples_any || $main_samples) {
    $query = "SELECT {node}.nid FROM {moonrock_sample} "
            . "LEFT JOIN {node} ON moonrock_sample.nid = node.nid ";
    $condition = "WHERE {node}.type = 'moonrock_sample' ";

    $parameters = array();

    if ($nid) {
      $query .= "LEFT JOIN {moonrock_snapshot} ON ({moonrock_snapshot}.sample_ref={moonrock_sample}.nid AND {moonrock_snapshot}.nid=%d) ";
      $condition .= "AND ({node}.nid=%d OR {moonrock_snapshot}.nid=%d) ";
      $parameters += array($nid, $nid, $nid);
    } else {
      if ($location) {
        $condition .= "AND {moonrock_sample}.location LIKE '%%%s%%' ";
        $parameters[] = $location;
      }

      if ($main_samples) {
        $condition .= "AND {node}.nid IN (" . db_placeholders($main_samples, "int") . ") ";
        $parameters += $main_samples;
      }
    }

    $result = db_query($query . $condition, $parameters);

    $matching_sample_nids = array();
    while ($object = db_fetch_object($result)) {
      $matching_sample_nids[] = $object->nid;
      $sample = node_load($object->nid);
      $samples[$sample->nid] = $sample;
    }

    $query2 = "SELECT {node}.nid, {node}.uid = %d as isOwner FROM {moonrock_snapshot} "
            . "LEFT JOIN {node} ON node.nid = moonrock_snapshot.nid "
            . "LEFT JOIN {users} ON users.uid = node.uid "
            . "LEFT JOIN {node} AS sample_node ON sample_node.nid = moonrock_snapshot.sample_ref ";

    global $user;
    $parameters2 = array();
    $parameters2[] = $user->uid;


    if ($nid) {
      $query2 .= "WHERE {moonrock_snapshot}.nid=%d ";
      $parameters2[] = $nid;
    } else {
      $query2 .= "WHERE {sample_node}.nid IN (" . db_placeholders($matching_sample_nids, "int") . ") ";
      $parameters2 = array_merge($parameters2, $matching_sample_nids);
    }
    
    $query2 .= "ORDER BY (isOwner) DESC ";


    $result2 = db_query($query2, $parameters2);
    while ($object2 = db_fetch_object($result2)) {
      $snapshot = node_load($object2->nid);

      $samples[$snapshot->sample_ref]->snapshots[] = $snapshot;
    }
  }

  $html_elements = moonrock_sample_utils_search_results_elements($samples, TRUE, $select_mode);

  drupal_json(array(
      'status' => true,
      'data' => array(
          "samples" => $samples,
          "elements" => $html_elements,
      ),
  ));
}

function moonrock_sample_ajax_newsnapshot_submit() {

  module_load_include('inc', 'node', 'node.pages');
  // load form
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  $form['#programmed'] = $form['#redirect'] = FALSE;
  // Process the form with drupal_process_form(), which calls the submit handlers that put whatever was worthy of keeping in the $form_state
  drupal_process_form($form_id, $form, $form_state);
  $errors = form_get_errors();
  if ($errors) {
    $output = '<div class="messages error"><ul>';
    foreach ($errors as $i => $message) {
      $output .= "<li>$message</li>";
    }
    $output .= '</ul></div>';
    $result = array("status" => FALSE, "data" => $output);
  } else {
    $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);
    global $user;

    $node = new stdClass();
    $node->uid = $user->uid;
    $node->type = 'moonrock_snapshot';
    $node->title = $form_state['post']['title'];
    $node->notes = $form_state['post']['notes'];
    $node->sample_ref = $form_state['post']['sample_ref'];
    $node->vm_parameters = $form_state['post']['vm_parameters'];

    node_save($node);

    $result = array(
        "status" => TRUE,
        "snapshot" => array(
            "nid" => $node->nid,
            "title" => $node->title,
        ),
    );
  }
  unset($_SESSION['messages']); // same as above
  drupal_json($result);
}

