<?php

function moonrock_data_form_load_resources() {
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/itemBrowser.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/itemBrowserItem.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/itemBrowserThrobber.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/MoonrockDataFormHistory.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/MoonrockDataFormSamples.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/MoonrockDataFormSearch.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/MoonrockDataFormData.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/MoonrockDataFormImage.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/MoonrockDataFormSnapshooting.js');
  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/init.js');

  drupal_add_js(drupal_get_path('module', 'moonrock_data_form') . '/js/jquery.ba-bbq.js');


  drupal_add_css(drupal_get_path('module', 'moonrock_data_form') . '/css/itemBrowser.css');
  drupal_add_css(drupal_get_path('module', 'moonrock_data_form') . '/css/moonrock_data_form_tabs.css');
  drupal_add_css(drupal_get_path('module', 'moonrock_data_form') . '/css/moonrock_data_form_snapshot_menu.css');
  drupal_add_css(drupal_get_path('module', 'moonrock_data_form') . '/css/moonrock_data_form_metadata.css');

  jquery_ui_add("ui.dialog");
  jquery_ui_add("ui.resizable");
  jquery_ui_add("ui.draggable");
  drupal_add_css(drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/jquery-ui.css');
  drupal_add_css(drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/ui.dialog.css');

  moonrock_vm_state_load_resources();
  moonrock_sample_utils_load_measure_format();
}

function _moonrock_data_form_create_mainsamples_table($main_samples) {
  $output = "<div class='moonrock-sample-list-header'>" . t('Rock samples:') . "</div>";
  $output .= "<div id='moonrock-sample-main-list'>";
  foreach ($main_samples as $sample) {
    $object = moonrock_sample_utils_prepare_object($sample->nid);
    $output .= "<div style='display:none;'>" . drupal_to_js($object) . "</div>";
  }
  $output .= '</div>';
  return $output;
}

function _moonrock_data_form_create_snapshot_tables() {
  $output = "<div class='moonrock-sample-list-header'>" . t('My snapshots:') . "</div>"
          . "<div id='moonrock-sample-mysnapshots-list-throbber'></div>"
          . "<div id='moonrock-sample-mysnapshots-list'></div>";

  $output .= "<div class='moonrock-sample-list-header'>" . t('Snapshots created by others:') . "</div>"
          . "<div id='moonrock-sample-snapshotsbyothers-list-throbber'></div>"
          . "<div id='moonrock-sample-snapshotsbyothers-list'></div>";
  return $output;
}

function _moonrock_data_form_snapshot_menu_button($buttonClassSufix, $label) {
  return "<div class='moonrock-snapshot-menu-item moonrock-snapshot-menu-$buttonClassSufix'>"
          . "<div class='moonrock-snapshot-menu-item-buttom'></div><div class='moonrock-snapshot-menu-item-label'>$label</div></div>";
}



function _moonrock_data_form_create_search_tab($main_samples, $snapshooting, $vm) {
  $output = ' <div id="moonrock-data-form-search" class="moonrock-data-form-search moonrock-data-form-hidden" vm="' . $vm . '">'
          . '  <div id="moonrock-data-form-search-items" class="moonrock-data-form-search-items">';

  $output.= _moonrock_data_form_create_mainsamples_table($main_samples);

  if ($snapshooting) {
    $output.= _moonrock_data_form_create_snapshot_tables();
  }

  $output.= '  </div>';

  if ($snapshooting) {
    $output .= '  <div id="moonrock-data-form-search-filter-container" class="moonrock-data-form-search-filter moonrock-data-form-false-block">'
            . '   <div id="moonrock-data-form-search-filter" class="block-inner">'
            . '    <h2 class="title">' . t('Snapshot search') . '</h2>'
            . '    <div class="content">'
            . _moonrock_data_form_snapshot_search($main_samples)
            . '    </div>'
            . '   </div>'
            . '  </div>';
  }
  $output .= ' </div>';
  return $output;
}

function _moonrock_data_form_create_vm_tab($wrappedForm, $snapshooting, $selectionEnabled) {
  $prefix = ' <div id="moonrock-data-form-vmform" class="moonrock-data-form-vmform moonrock-data-form-hidden">'
          . '  <div id="moonrock-data-form-vm" class="moonrock-data-form-vm">'
          . '   <div id="moonrock-data-form-vm-expand" class="moonrock-data-form-vm-expand"><div class="icon"></div>' . t('Expand') . '</div>'
          . '   <div id="moonrock-data-form-vm-restore" class="moonrock-data-form-vm-restore"><div class="icon"></div>' . t('Restore') . '</div>';

  if ($selectionEnabled) {
    $prefix .= '   <div id="moonrock-data-form-sample" class="moonrock-data-form-item">'
            . '    <div id="moonrock-data-form-sample-previous" class="moonrock-data-form-item-button moonrock-data-form-item-previous"></div>'
            . '    <div class="moonrock-data-form-item-title">' . t('Browsing ') . '</div>'
            . '    <div id="moonrock-data-form-sample-title" class="moonrock-data-form-item-title"></div>'
            . '    <div id="moonrock-data-form-sample-next" class="moonrock-data-form-item-button moonrock-data-form-item-next"></div>'
            . '   </div>';
  }
  if ($snapshooting && $selectionEnabled) {

    $prefix .= /* '   <div id="moonrock-data-form-snapshot" class="moonrock-data-form-item">'
              . '     <div id="moonrock-data-form-snapshot-previous" class="moonrock-data-form-item-button moonrock-data-form-item-previous"></div>'
              . '     <div id="moonrock-data-form-snapshot-title" class="moonrock-data-form-item-title"></div>'
              . '     <div id="moonrock-data-form-snapshot-next" class="moonrock-data-form-item-button moonrock-data-form-item-next"></div>'
              . '    </div>'
              . */ '   <div class="moonrock-snapshot-menu">'
//            . _moonrock_data_form_snapshot_menu_button('new', t('New snapshot'))
            //          . _moonrock_data_form_snapshot_menu_button('edit', t('Update this snapshot'))
            //        . _moonrock_data_form_snapshot_menu_button('center', t('Center view'))
            . _moonrock_data_form_snapshot_menu_button('search', t('Search snapshots of this view'))
            . '    </div>';
  }
  $prefix .= '    <div id="moonrock-data-form-vm-container" class="moonrock-data-form-vm-container">'
          . '     <iframe id="moonrock-data-form-vm-iframe"></iframe>'
          . '    </div>'
          . '    <div id="moonrock-data-form-vm-resize"><canvas id="moonrock-data-form-vm-resize-canvas"></canvas></div>'
          . '  </div>';
  if ($wrappedForm) {
    $prefix.= '  <div id="moonrock-data-form-form" class="moonrock-data-form-form moonrock-data-form-false-block">'
            . '   <div id="moonrock-data-form-block" class="block-inner">'
            . '    <h2 class="title">' . t('Data') . '</h2>'
            . '    <div class="content">'
            . $wrappedForm;
    $suffix = '    </div>'
            . '   </div>'
            . '  </div>'// end of moonrock-data-form-form
            . ' </div>';
  } else {
    $suffix = ' </div>';
  }


  if ($wrappedForm) {
    return array('prefix' => $prefix, 'suffix' => $suffix);
  } else {
    return $prefix . $suffix;
  }
}

function _moonrock_data_form_create_page($form_prefix, $snapshooting, $vm, $selectionEnabled) {
  moonrock_data_form_load_resources();

  //$details = get_inquiry_details_from_current_path();
  //$activity = load_activity($details->activity_id);

  $sample_view = moonrock_sample_utils_find_unique_seesamples_activity();
  if ($sample_view) {
    $main_samples = moonrock_seesamples_get_main_samples($sample_view);
    //$search = moonrock_seesamples_search_enabled($sample_view);
  } else {
    $main_samples = array();
    //$search = TRUE;
  }

  $prefix = '<div id="moonrock-data-form-page" class="moonrock-data-form-page">'
          . _moonrock_data_form_create_search_tab($main_samples, $snapshooting, $vm);

  if ($form_prefix || $vm) {
    $innerwrap = _moonrock_data_form_create_vm_tab($form_prefix, $snapshooting, $selectionEnabled);
  } else {
    $innerwrap = '';
  }

  $suffix = '</div>';

  /* if ($snapshooting) {
    $suffix .= '<div id="moonrock-sample-newsnapshot-dlg">' . drupal_get_form('moonrock_snapshot_form') . '</div>';
    } */

  if ($form_prefix) {
    return array('prefix' => $prefix . $innerwrap['prefix'], 'suffix' => $innerwrap['suffix'] . $suffix);
  } else {
    return $prefix . $innerwrap . $suffix;
  }
}

function moonrock_data_form_form_pi_data_node_form_alter(&$form, &$form_state) {
  $form['buttons']['submit']['#attributes'] = array('onClick' => 'MoonrockDataFormData.submitData();return false;');
  return;
}

function moonrock_data_form_wrap_form($form_prefix, $selectionEnabled) {
  return _moonrock_data_form_create_page($form_prefix, TRUE, TRUE, $selectionEnabled);
}

function moonrock_data_form_seesamples_activity() {
  return _moonrock_data_form_create_page(FALSE, FALSE, TRUE, TRUE);
}

function moonrock_data_form_add_question_info() {
  return _moonrock_data_form_create_page(FALSE, FALSE, FALSE, FALSE);
}

function _moonrock_data_form_snapshot_search($main_samples, $sample_search = FALSE) {
  $visible = '';
  $hidden = '';

  if ($main_samples || $sample_search) {
    $visible .= '<div class="moonrock-data-form-snapshot-filter-key">' . t('Snapshots of samples:') . '</div>'
            . '<div class="moonrock-data-form-snapshot-filter-input">';

    if ($main_samples) {
      if ($sample_search) {
        $visible .= '<input type="checkbox" name="useanysampleref" value="any" '
                . "id='moonrock-sample-search-snapshots-usesamplerefs' />"
                . "<label for='moonrock-sample-search-snapshots-usesamplerefs'>" . t('Any') . "</label><br/>";
      }
      foreach ($main_samples as $sample) {
        $id = "moonrock-sample-search-snapshots-main-samples-{$sample->nid}";
        $visible .= '<input type="checkbox" name="mainsamples[]" '
                . "id='$id' value='{$sample->nid}' checked='checked'/>"
                . "<label for='$id'>{$sample->title}</label><br/>";
      }
    } else if ($sample_search) {
      $visible .= '<select id="moonrock-sample-search-snapshots-usesamplerefs" name="usesamplerefs">'
              . '<option value="1">' . t('Shown samples') . '</option>'
              . '<option value="0">' . t('Any sample') . '</option>'
              . '</select>';
    }

    $visible .= '</div>';
  }



  $visible .= '<div class="moonrock-data-form-snapshot-filter-key">' . t('Keyword:') . '</div>'
          . '<div class="moonrock-data-form-snapshot-filter-input">';
  $visible .= '<input type="text" id="moonrock-sample-search-snapshots-keyword" name="keyword" />';
  $visible .= '</div>';


  $visible .= '<div class="moonrock-data-form-snapshot-filter-key">' . t('Sample view:') . '</div>'
          . '<div class="moonrock-data-form-snapshot-filter-input">';
  $explanation = '<p>' . t('No view has been selected.') . '</p><p>' . t('To filter snapshots by view:')
          . '</p><ul>'
          . '<li>' . t('Open a microscope for any sample or snapshot.') . '</li>'
          . '<li>' . t('Zoom to an interesting spot.') . '</li>'
          . '<li>' . t('Click on the button:') . '<br/><b>' . t('Search snapshots of this view') . '</b>'
          . '</li></ul>';
  $visible .= '<div class="moonrock-sample-search-snapshots-view-tab" id="moonrock-sample-search-snapshots-view-noview">'
          . $explanation
          . '</div>'
          . '<div class="moonrock-sample-search-snapshots-view-tab" id="moonrock-sample-search-snapshots-view-view">'
          . '  <div style="width:150px;">'
          . '    <img id="moonrock-sample-search-snapshots-view-img" style="width:100%;" />'
          . '    <div style="width: 100%; text-align: center;">'
          . '      <div id="moonrock-sample-search-snapshots-view-sample" style="display: inline-block;padding-left:10px;"></div><div class="item-browser-item-title-open"></div>'
          . '    </div>'
          . '  </div>'
          . '<div><p>'
          . t('With ') . '<select id="moonrock-sample-search-snapshots-view-zoom" name="viewzoom">'
          . '<option value="0">' . t('same zoom') . '</option>'
          . '<option value="1">' . t('similar zoom') . '</option>'
          . '<option value="2">' . t('any zoom') . '</option>'
          . '</select>'
          . t(' and ') . '<select id="moonrock-sample-search-snapshots-view-position" name="viewposition">'
          . '<option value="0">' . t('same position') . '</option>'
          . '<option value="1">' . t('similar positions') . '</option>'
          . '<option value="2">' . t('any position') . '</option>'
          . '</select>'
          . '</p></div>'
          . '<div><button type="button" id="moonrock-sample-search-snapshots-view-clear">' . t('Remove view filter') . '</button></div>'
          . '</div>';
  $visible .= '</div>';

  $hidden .= '<input type="hidden" id="moonrock-sample-search-snapshots-useviewsample" name="useviewsample" />';
  $hidden .= '<input type="hidden" id="moonrock-sample-search-snapshots-useviewparameters" name="useviewparameters" />';



  $search = '<form class="moonrock-sample-search-form" id="moonrock-sample-search-snapshots-form">'
          . $hidden
          . $visible
          . '</form>'
          . '<div style="text-align: center;">'
          . '<button id="moonrock-sample-search-snapshots-search">' . t('Search') . '</button>'
          . '</div>';

  return $search;
}

function moonrock_data_form_nodeapi(&$node, $op, $a3, $a4) {
  if ($op === 'presave' && $node->form_id === 'pi_data_node_form') {
    global $user;
    $node_details = get_inquiry_details_from_current_path();
    $measures_param = find_selected_measures_nid_for_uid_and_inquiry($user->uid, $node_details->inquiry_id);
    if ($measures_param) {
      $measures_node = node_load($measures_param);
      $measure_rows = $measures_node->measures_list;


      $sample_key = '';
      $snapshot_key = '';

      foreach ($measure_rows as $measure_info_nid => $measure_selection) {
        if ($measure_selection['#status'] == 'key' || $measure_selection['#status'] == 'selected') {
          $measure_info = node_load($measure_info_nid);
          if ($measure_info->content_options === 'moonrock_sample') {
            $sample_key = "$measures_param-$measure_info_nid";
          } else if ($measure_info->content_options === 'moonrock_snapshot') {
            $snapshot_key = "$measures_param-$measure_info_nid";
          }
        }
      }

      $sample_nid = $node->onepageprofile_categories[$sample_key]['value'];
      $snapshot_nid = $node->onepageprofile_categories[$snapshot_key]['value'];

      $snapshot = node_load($snapshot_nid);
      if (!$snapshot) {
        $snapshot = new stdClass();
        $snapshot->uid = $user->uid;
        $snapshot->type = 'moonrock_snapshot';
      }
      $snapshot->notes = $node->onepageprofile_categories['moonrock_snapshot_notes']['value'];
      $snapshot->vm_parameters = $node->onepageprofile_categories['moonrock_snapshot_notes']['value'];
      $snapshot->sample_ref = $sample_nid;
      node_save($snapshot);
      $node->onepageprofile_categories[$snapshot_key]['value'] = $snapshot->nid;
      moonrock_snapshot_images_savesnapshot($node->onepageprofile_categories['moonrock_snapshot_image']['value'], $snapshot->nid);
      return;
    }
  }
}