<?php

function moonrock_layout_theme() {
  return array(
      'moonrock_layout_vertical' => array(
          'arguments' => array('elements', 'isRoot'),
      ),
      'moonrock_layout_horizontal' => array(
          'arguments' => array('elements', 'isRoot'),
      ),
      'moonrock_layout_tabs' => array(
          'arguments' => array('tabs', 'content', 'enable_fullscreen'),
      ),
  );
}

function theme_moonrock_layout_vertical($elements, $isRoot) {
  return _moonrock_layout_direction($elements, 'vertical', $isRoot);
}

function theme_moonrock_layout_horizontal($elements, $isRoot) {
  return _moonrock_layout_direction($elements, 'horizontal', $isRoot);
}

function theme_moonrock_layout_tabs($tabs, $content, $enable_fullscreen) {
  _moonrock_layout_load_resources();

  $container_class = 'layout-tabbed-container';
  if ($enable_fullscreen) {
    $container_class .= ' layout-tabbed-container-fullscreen-enabled';
  }


  $output = '<div class="' . $container_class . '">';

  if ($enable_fullscreen) {
    $output .= '<div class="layout-tabbed-container-fullscreen-button"></div>';
  }


  $output .= '<div class="layout-tabbed-container-tabs">';


  foreach ($tabs as $tab) {
    $classname = 'layout-tabbed-container-tab';
    if ($tab['hidden']) {
      $classname .= ' layout-tabbed-container-hidden';
    }

    $output .= '<div class="' . $classname . '" tab="' . $tab['tabId'] . '" content="' . $tab['contentId'] . '">'
            . $tab['title']
            . '</div>';
  }
  $output .= '</div>';

  $output .= '<div class="layout-tabbed-container-contents">';
  foreach ($content as $i => $content) {
    $output .= '<div class="layout-tabbed-container-content" content="' . $content['contentId'] . '">'
            . $content['content']
            . '</div>';
  }
  $output .= '</div>';

  $output .= '</div>';

  return $output;
}

function _moonrock_layout_direction($elements, $direction, $isRoot) {
  _moonrock_layout_load_resources();

  $output = '';
  $boxclass = 'layout-box layout-box-' . $direction;
  if ($isRoot) {
    $boxclass .= ' layout-root';
  }

  $output .= '<div class="' . $boxclass . '">';

  foreach ($elements as $element) {
    $classname = 'layout-block layout-block-' . $direction;
    if ($element['flex']) {
      $classname .= ' layout-block-flex';
    } else {
      $classname .= ' layout-block-fixed';
    }

    $style = '';
    if (isset($element['width'])) {
      $style .= 'width:' . $element['width'] . 'px;';
    }
    if (isset($element['height'])) {
      $style .= 'height:' . $element['height'] . 'px;';
    }

    if (isset($element['id'])) {
      $id = 'id="' . $element['id'] . '"';
    } else {
      $id = '';
    }

    $output .= '<div ' . $id . ' class="' . $classname . '" style="' . $style . '">'
            . $element['content']
            . '</div>';
  }

  $output .= '</div>';

  return $output;
}

function _moonrock_layout_load_resources() {
  drupal_add_css(drupal_get_path('module', 'moonrock_layout') . '/css/layout.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_layout') . '/js/layout.js');
}