<?php

require_once( 'lib/pChart/pData.class.php');
require_once( 'lib/pChart/pDraw.class.php');
require_once( 'lib/pChart/pImage.class.php');

/*
  require_once( 'lib/pChart/pData.class.1.26.php');
  require_once( 'lib/pChart/pChart.class.1.26.php');
 */

function pi_chart_menu() {
  $items['activity/%/chart.png'] = array(
      'page callback' => 'pi_chart_show_chart_as_png',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );

  $items['pi_chart/tempchart.png'] = array(
      'page callback' => 'pi_chart_show_chart_as_temppnlg',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );

  $items['activity/%/tempchart.png'] = array(
      'page callback' => 'pi_chart_show_chart_as_temppng',
      'page arguments' => array(1, 2),
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
  );


  return $items;
}

function pi_chart_show_chart_as_temppng() {
  $title = $_REQUEST['title'];
  $type = $_REQUEST['type'];
  $abscissa_nid = $_REQUEST['abscissa'];
  $ordinate_str = $_REQUEST['ordinate'];
  $color_nid = $_REQUEST['color'];

  global $user;

  if (strlen($type) > 0 && strlen($abscissa_nid) > 0 && strlen($ordinate_str) > 0) {
    pi_chart_create_png($title, $type, $abscissa_nid, $ordinate_str, $color_nid, $user->uid);
  }
  return;
}

function pi_chart_create_png($title, $type, $abscissa_nid, $ordinate_str, $color_nid, $uid) {
  $ordinate_count = count(explode(',', $ordinate_str));

  $details = get_inquiry_details_from_current_path();

  $selected_measures = $abscissa_nid . ',' . $ordinate_str;
  if (strlen($color_nid) > 0) {
    $selected_measures .= ',' . $color_nid;
  }

  $headers = get_selected_measures_headings_for_inquiry_and_user($details->inquiry_id, $selected_measures, $uid);
  $rows = get_selected_measures_data_for_inquiry_and_user($details->inquiry_id, $selected_measures, $uid);
  $types = get_selected_measures_types_for_inquiry_and_user($details->inquiry_id, $selected_measures, $uid);

  /*
   * Group by key measure
   */

  if ($type == 'line-bar') {
    $key_numeric = $types[0]->data_type == 'numeric';

    $color_field = strlen($color_nid) > 0 ? 1 + $ordinate_count : FALSE;

    $numeric_fields = array();
    for ($i = 0; $i < $ordinate_count; $i++) {
      $numeric_fields[] = $i + 1;
    }

    $grouped_rows = array();
    foreach ($rows as $row) {
      if (strlen($row[0]) > 0) {
        $row_has_data = FALSE;
        foreach ($numeric_fields as $field) {
          if (strlen($row[$field]) > 0) {
            $row_has_data = TRUE;
            break;
          }
        }
        if ($row_has_data) {
          $grouped_rows[$row[0]][] = $row;
        }
      }
    }

    /*
     * determine chart type
     */
    if ($key_numeric) {
      $type = 'scatter';
    } else {
      $max_data_count_per_key_field = 0;
      foreach ($grouped_rows as $row_group) {
        if (count($row_group) > $max_data_count_per_key_field) {
          $max_data_count_per_key_field = count($row_group);
        }
      }

      if ($max_data_count_per_key_field > 1) {
        $type = 'plot';
      } else {
        $type = 'bar';
      }
    }

    switch ($type) {
      case 'bar':
        _pi_chart_draw_bar_chart($title, $headers, $grouped_rows, $types, $numeric_fields, $color_field);
        break;
      case 'plot':
        _pi_chart_draw_plot_chart($title, $headers, $grouped_rows, $types, $numeric_fields, $color_field);
        break;
      default:
        break;
    }
  } else if ($type === 'histogram') {
    $data_index = array(array(), array());
    $data_values = array(array(), array());

    $numeric_data_limits = array(FALSE, FALSE);
    $ngaps = 5;

    for ($i = 0; $i < 2; $i++) {
      if (_pi_chart_type_is_numeric($types[$i])) {
        $min = 0.0;
        $max = 0.0;
        foreach ($rows as $row) {
          if (strlen($row[$i]) > 0) {
            $min = min($min, _pi_chart_get_numeric_value($row[$i], $types[$i]));
            $max = max($max, _pi_chart_get_numeric_value($row[$i], $types[$i]));
          }
        }

        $max_abs_value = max(abs($max), abs($min));
        if ($max_abs_value > 0) {
          $log = log10($max_abs_value);
          $f10 = pow(10, ceil($log));
          $min = floor($min / $f10) * $f10;
          $max = ceil($max / $f10) * $f10;
        }

        $gap = $max > $min ? ($max - $min) / $ngaps : 5;
        $limits = array();
        $ft = function($f) {
          $t = "$f";
          if (strlen($t) > 1 && $t[0] == '0') {
            $t = substr($t, 1);
          }
          return $t;
        };
        
        for ($j = 0; $j < $ngaps; $j++) {
          $l0 = $min + $j * $gap;
          $l1 = $l0 + $gap;

          $limits[$j] = $l1;
          $data_values[$i][$j] = $ft($l0) . ' - ' . $ft($l1);
        }
        $numeric_data_limits[$i] = $limits;
      } else {
        foreach ($rows as $row) {
          if (strlen($row[$i]) > 0) {
            $v = $row[$i];
            if (!isset($data_index[$i][$v])) {
              $j = count($data_index[$i]);
              $data_index[$i][$v] = $j;
              $data_values[$i][$j] = _pi_chart_get_text_value($v, $types[$i]);
            }
          }
        }
      }
    }
    $cross = array_fill(0, max(1, count($data_index[0])), array_fill(0, max(1, count($data_index[1])), 0));
    foreach ($rows as $row) {
      $indexes = array(-1, -1);
      for ($i = 0; $i < 2; $i++) {
        if (strlen($row[$i]) > 0) {
          if ($numeric_data_limits[$i]) {
            $v = _pi_chart_get_numeric_value($row[$i], $types[$i]);
            for ($j = 0; $j < $ngaps - 1; $j++) {
              if ($numeric_data_limits[$i][$j] >= $v) {
                break;
              }
            }
            $indexes[$i] = $j;
          } else {
            $indexes[$i] = $data_index[$i][$row[$i]];
          }
        }
      }

      if ($indexes[0] >= 0 && $indexes[1] >= 0) {
        $cross[$indexes[0]][$indexes[1]]++;
      }
    }

    /* for ($i = 0; $i < count($cross); $i++) {
      for ($j = 0; $j < count($cross[$i]); $j++) {
      if ($cross[$i][$j] == 0) {
      $cross[$i][$j] = VOID;
      }
      }
      } */

    $colors = FALSE;
    if ($types[1]->content_options) {
      $function_name = "{$types[1]->content_options}_nquire_data_get_color_value";
      if (function_exists($function_name)) {
        $colors = array();
        foreach ($data_index[1] as $nid => $index) {
          $colors[$index] = _pi_chart_get_color_value($nid, $types[1]);
        }
      }
    }

    _pi_chart_draw_histogram($title, $headers, $numeric_data_limits, $cross, $data_values, $colors);
  }

  return;
}

function pi_chart_show_chart_as_png($activity_id, $arg_node_function) {
  global $user;

  $details = get_inquiry_details_from_current_path();

  $nid = get_nid_for_inquiry_activity_and_any_user($details->inquiry_id, $activity_id);
  $node = node_load($nid);
  pi_chart_create_png($node->title, $node->chart_type, $node->abscissa, $node->ordinate, $node->color, $node->uid);
}

function _pi_chart_get_numeric_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_numeric_value";
    return $function_name($value);
  } else {
    return strlen($value) > 0 ? floatval($value) : VOID;
  }
}

function _pi_chart_get_color_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_color_value";
    return $function_name($value);
  } else {
    return array("R" => 255, "G" => 255, "B" => 255, "Alpha" => 127);
  }
}

function _pi_chart_get_text_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_text_value";
    return $function_name($value);
  } else {
    return check_plain($value);
  }
}

function _pi_chart_get_html_value($value, $type) {
  if ($type->content_options) {
    $function_name = "{$type->content_options}_nquire_data_get_html_value";
    return $function_name($value);
  } else {
    return _pi_chart_get_text_value($value, $type);
  }
}

function pi_chart_get_text_value($value, $type) {
  return _pi_chart_get_text_value($value, $type);
}

function pi_chart_get_html_value($value, $type) {
  return _pi_chart_get_html_value($value, $type);
}

function _pi_chart_prepare_histogram_variable_name($name, $isNumeric) {
  $a = strpos($name, '(');
  if ($a !== FALSE) {
    $b = strpos($name, ')', $a);
    if ($b !== FALSE) {
      $name = trim(substr($name, 0, $a) . substr($name, $b + 1));
    }
  }

  if ($isNumeric) {
    $name .= t(' range');
  }

  return $name;
}

function _pi_chart_draw_histogram($title, $headers, $numeric, $cross, $data_values, $colors) {
  /* Create and populate the pData object */

  if ($numeric[0] && !$numeric[1]) {
    $name1 = $headers[0];
    $numeric1 = TRUE;
    $name0 = $headers[1];
  } else {
    $name1 = $headers[1];
    $numeric1 = $numeric[1];
    $name0 = $headers[0];
  }
  $headers[1] = t('No. of ') . $name0 . t("\nper ") . _pi_chart_prepare_histogram_variable_name($name1, $numeric1);

  $MyData = new pData();
  $max = 1;

  /* Add series. There must be only one row group for each key, so we use only $row_group[0]. */
  for ($i = 0; $i < count($data_values[1]); $i++) {
    $series = array();
    for ($j = 0; $j < count($data_values[0]); $j++) {
      $series[] = $cross[$j][$i];
      $max = max($max, $cross[$j][$i]);
    }
    $MyData->addPoints($series, $data_values[1][$i]);
    $MyData->setAxisName(0, $headers[1]);
    if ($colors) {
      $MyData->setPalette($data_values[1][$i], $colors[$i]);
    } else {
      $MyData->setPalette($data_values[1][$i], array("R" => 0, "G" => 200, "B" => 0, "Alpha" => 100));
    }
  }

  $abscissa_series = array();
  for ($j = 0; $j < count($data_values[0]); $j++) {
    $abscissa_series[] = $data_values[0][$j];
  }

  $MyData->addPoints($abscissa_series, $headers[0]);
  $MyData->setSerieDescription($headers[0], $headers[0]);
  $MyData->setAbscissa($headers[0]);
  $MyData->setAbscissaName($headers[0]);

  $myPicture = new pImage(900, 350, $MyData);

  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 899, 349, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 850, 310);
  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => FALSE,
      "CycleBackground" => TRUE,
      "Mode" => SCALE_MODE_MANUAL,
      "ManualScale" => array(0 => array("Min" => 0, "Max" => $max + 1)),
      "MinDivHeight" => 105.0 / ($max + 1),
  );
  $myPicture->drawScale($scaleSettings);
  $myPicture->drawText(450, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));

  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  /* Draw the chart */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  $settings = array(
      "DisplayPos" => LABEL_POS_TOP,
      "DisplaySeriesName" => TRUE,
      "DisplayR" => 15,
      "DisplayG" => 15,
      "DisplayB" => 15,
      "DisplayShadow" => TRUE,
      //"Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
          //"InnerSurrounding" => 100,
  );

  $settings["Gradient"] = TRUE;
  $settings["GradientMode"] = GRADIENT_SIMPLE;

  $myPicture->drawBarChart($settings);
  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

function _pi_chart_type_is_numeric($type) {
  return $type->data_type == 'numeric' || ($measure->content_options && function_exists("{$measure->content_options}_nquire_data_get_numeric_value"));
}

function _pi_chart_draw_bar_chart($title, $headers, $grouped_rows, $types, $numeric_fields, $color_field) {
  /* Create and populate the pData object */
  $MyData = new pData();

  /* Add series. There must be only one row group for each key, so we use only $row_group[0]. */
  foreach ($numeric_fields as $field) {
    $series = array();
    foreach ($grouped_rows as $row_group) {
      if (count($row_group) > 0) {
        $value = $row_group[0][$field];
        $series[] = _pi_chart_get_numeric_value($value, $types[$field]);
      }
    }
    $MyData->addPoints($series, $headers[$field]);
    $MyData->setAxisName(0, $headers[$field]);
  }

  $abscissa_series = array();
  foreach ($grouped_rows as $key => $row_group) {
    if (count($row_group) > 0) {
      $abscissa_series[] = _pi_chart_get_text_value($key, $types[0]);
    }
  }

  $MyData->addPoints($abscissa_series, $headers[0]);
  $MyData->setSerieDescription($headers[0], $headers[0]);
  $MyData->setAbscissa($headers[0]);
  $MyData->setAbscissaName($headers[0]);



  if ($color_field) {
    $palette = array();

    foreach ($grouped_rows as $row_group) {
      $value = $row_group[0][$color_field];
      $palette[] = _pi_chart_get_color_value($value, $types[$color_field]);
    }
  } else {
    $palette = NULL;
  }



  $myPicture = new pImage(700, 250, $MyData);


  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 699, 249, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 650, 210);

  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => TRUE,
      "CycleBackground" => TRUE,
      "Mode" => SCALE_MODE_START0,
  );
  $myPicture->drawScale($scaleSettings);
  $myPicture->drawText(350, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));

  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  /* Draw the chart */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  $settings = array(
      "DisplayPos" => LABEL_POS_TOP,
      "DisplayValues" => TRUE,
      "DisplayR" => 15,
      "DisplayG" => 15,
      "DisplayB" => 15,
      "DisplayShadow" => TRUE,
      //"Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
          //"InnerSurrounding" => 100,
  );

  if ($color_field) {
    $settings["OverrideColors"] = $palette;
  } else {
    $settings["Gradient"] = TRUE;
    $settings["GradientMode"] = GRADIENT_SIMPLE;
  }
  $myPicture->drawBarChart($settings);
  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

function _pi_chart_draw_plot_chart($title, $headers, $grouped_rows, $types, $numeric_fields, $color_field) {
  /* Create and populate the pData object */
  $MyData = new pData();

  /**
   * simple processing: one serie per value.
   */
  $series_counter = 1;
  $keys = array_keys($grouped_rows);

  foreach ($numeric_fields as $field) {
    for ($key_index = 0; $key_index < count($keys); $key_index++) {
      $row_group = $grouped_rows[$keys[$key_index]];
      usort($row_group, function($a, $b) {
                if ($a[$field] < $b[$field]) {
                  return 1;
                } else if ($a[field] > $b[field]) {
                  return -1;
                } else {
                  return 0;
                }
              });

      foreach ($row_group as $row) {
        $value = $row[$field];
        $series = $key_index > 0 ? array_fill(0, $key_index, VOID) : array();
        $series[] = _pi_chart_get_numeric_value($value, $types[$field]);
        if ($key_index < count($keys) - 1) {
          $series = array_merge($series, array_fill(0, count($keys) - 1 - $key_index, VOID));
        }
        $MyData->addPoints($series, $series_counter);
        if ($color_field) {
          $MyData->setPalette($series_counter, _pi_chart_get_color_value($row[$color_field], $types[$color_field]));
        } else {
          $MyData->setPalette($series_counter, array("R" => 0, "G" => 200, "B" => 0, "Alpha" => 127));
        }

        $series_counter++;
      }
    }
    $MyData->setAxisName(0, $headers[$field]);
  }

  $abscissa_series = array();
  for ($key_index = 0; $key_index < count($keys); $key_index++) {
    $abscissa_series[] = _pi_chart_get_text_value($keys[$key_index], $types[0]);
  }
  $MyData->addPoints($abscissa_series, $headers[0]);
  $MyData->setSerieDescription($headers[0], $headers[0]);
  $MyData->setAbscissa($headers[0]);
  $MyData->setAbscissaName($headers[0]);


  $myPicture = new pImage(700, 250, $MyData);

  /* Add a border to the picture */
  $myPicture->drawRectangle(0, 0, 699, 249, array("R" => 0, "G" => 0, "B" => 0));

  /* Set the default font */
  $myPicture->setFontProperties(array("FontName" => dirname(__FILE__) . '/lib/Fonts/tahoma.ttf', "FontSize" => 10));

  /* Define the chart area */
  $myPicture->setGraphArea(60, 40, 650, 210);

  /* Draw the scale */
  $scaleSettings = array(
      "GridR" => 200,
      "GridG" => 200,
      "GridB" => 200,
      "DrawSubTicks" => TRUE,
      "CycleBackground" => TRUE,
      "Mode" => SCALE_MODE_START0,
  );
  $myPicture->drawScale($scaleSettings);
  $myPicture->drawText(350, 5, $title, array("FontSize" => 12, "Align" => TEXT_ALIGN_TOPMIDDLE));
  /* Write the chart legend */
  //$myPicture->drawLegend(580, 12, array("Style" => LEGEND_NOBORDER, "Mode" => LEGEND_HORIZONTAL));

  /* Turn on shadow computing */
  $myPicture->setShadow(TRUE, array("X" => 1, "Y" => 1, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10));

  $settings = array(
      "DisplayPos" => LABEL_POS_TOP,
      "DisplayValues" => TRUE,
      "DisplayR" => 15,
      "DisplayG" => 15,
      "DisplayB" => 15,
      "DisplayShadow" => TRUE,
      //"Rounded" => TRUE,
      "BorderR" => 35,
      "BorderG" => 35,
      "BorderB" => 35,
      "InnerBorderR" => 215,
      "InnerBorderG" => 215,
      "InnerBorderB" => 215,
      "BorderSize" => 2,
      "PlotSize" => 7,
      "PlotBorder" => TRUE,
  );

  $myPicture->drawPlotChart($settings);
  /* Render the picture (choose the best way) */
  $myPicture->Stroke();
}

?>
