<?php

define("MOONROCK_SEARCH_NONE", 0x00);
define("MOONROCK_SEARCH_SAMPLE", 0x01);
define("MOONROCK_SEARCH_SNAPSHOT", 0x02);
define("MOONROCK_SEARCH_BOTH", 0x03);

function _moonrock_sample_utils_sample_dialog_button($buttonClassSufix, $label) {
  return "<div class='moonrock-sample-dlg-menu-item moonrock-sample-dlg-menu-$buttonClassSufix'>"
          . "<div class='moonrock-sample-dlg-menu-item-buttom'></div><div class='moonrock-sample-dlg-menu-item-label'>$label</div></div>";
}

function moonrock_sample_utils_create_sample_dialog($nid, $create_snashot_menu) {
  $node = node_load($nid);

  if ($node->type == 'moonrock_snapshot') {
    $snapshot = $node;
    $sample = node_load($snapshot->sample_ref);
  } else if ($node->type == 'moonrock_sample') {
    $snapshot = FALSE;
    $sample = $node;
  } else {
    $snapshot = $sample = FALSE;
  }
  $output = '';

  if ($sample) {
    global $user;
    $itemid = $snapshot ? $snapshot->nid : $sample->nid;
    $own_snapshot = $snapshot && $snapshot->uid === $user->uid;
    $output .= "<div class='moonrock-sample-dlg' own-snapshot='{$own_snapshot}' item-id='{$itemid}' sample='{$sample->nid}' sample_name='" . check_plain($sample->title) . "'";
    if ($snapshot) {
      $output .= " snapshot='{$snapshot->nid}' snapshot_name='" . check_plain($snapshot->title) . "'";
    }
    $output .= ">";

    $output .= "  <div class='moonrock-sample-iframe-top-container'>";
    if ($create_snashot_menu) {
      $output .= "    <div class='moonrock-sample-dlg-menu'>";
      $output .= _moonrock_sample_utils_sample_dialog_button('new', t('New snapshot'));
      $output .= _moonrock_sample_utils_sample_dialog_button('edit', t('Update this snapshot'));
      $output .= _moonrock_sample_utils_sample_dialog_button('center', t('Center view'));
      $output .= _moonrock_sample_utils_sample_dialog_button('search', t('Search snapshots of this view'));
      $output .= "    </div>";
    }

    $output .= "    <div class='moonrock-sample-snapshot-notes'>";
    if ($snapshot) {
      $output .= check_plain($snapshot->notes);
    }
    $output .= "</div>";

    $output .= "    <div class='moonrock-sample-iframe-container'>";
    $output .= "      <iframe class='moonrock-sample-iframe' src='{$sample->vm}'></iframe>";
    $output .= "    </div>";
    $output .= "  </div>";
    $output .= "</div>";
  }

  return $output;
}

function moonrock_sample_utils_find_unique_seesamples_activity() {
  global $user;
  $node_details = get_inquiry_details_from_current_path();
  $sample_view_nid = find_unique_node_type_for_uid_and_inquiry('moonrock_seesamples', $user->uid, $node_details->inquiry_id);
  if ($sample_view_nid) {
    module_load_include('inc', 'moonrock_seesamples', 'moonrock_seesamples.table');
    return node_load($sample_view_nid);
  } else {
    return FALSE;
  }
}

function moonrock_sample_utils_create_table_for_current_inquiry($link_vm, $select_mode) {
  $sample_view = moonrock_sample_utils_find_unique_seesamples_activity();
  if ($sample_view) {
    $main_samples = moonrock_seesamples_get_main_samples($sample_view);
    $search = moonrock_seesamples_search_enabled($sample_view);
  } else {
    $main_samples = array();
    $search = TRUE;
  }

  return moonrock_sample_utils_create_sample_table($main_samples, $link_vm, $search, TRUE, $select_mode);
}

function moonrock_sample_utils_add_info_tooltip($title, $content) {
  $output = "<span class='qtip-link'>"
          . "<div class='qtip-header'>$title</div>"
          . "<div class='qtip-tooltip'>$content</div>"
          . "<div class='item-browser-item-title-cluetip'></div>"
          . "</span>";

  return $output;
}

/**
 * 
 * @param type $select_mode Possible values: 'none', 'sample', 'snapshot'
 * @param type $select_name
 */
function moonrock_sample_utils_create_sample_table($main_samples, $link_vm, $sample_search, $snapshot_search, $select_mode) {
  moonrock_sample_utils_load_resources($link_vm, $sample_search, $snapshot_search, $select_mode);

  $output = '';

  if ($select_mode & MOONROCK_SEARCH_SAMPLE) {
    $output .= "<div><b>" . t("Select a sample:") . "</b>"
            . moonrock_sample_utils_add_info_tooltip('Rock sample', '<p>This measure simply represents the selection of the Moon rock for which you are collecting data.</p>'
                    . '<p>When you make a measurement (for instance, the size of a grain in a rock), use the <b>Rock sample</b> to specify the rock in which the measure was made.</p>')
            . "</div>";
  }

  if ($main_samples != NULL) {
    $select = $select_mode & MOONROCK_SEARCH_SAMPLE ? 'true' : 'false';
    $output .= "<div id='moonrock-sample-main-list' select='{$select}'>";
    foreach ($main_samples as $sample) {
      $output .= "<div item-def='" . drupal_to_js(moonrock_sample_utils_prepare_sample_object($sample->nid)) . "' item-id='{$sample->nid}' title='{$sample->title}' img='{$sample->snapshot}'></div>";
    }
    $output .= '</div>';
  }


  if ($sample_search) {
    $search = '<div class="moonrock-sample-search-dlg" id="moonrock-sample-search-samples-dlg" title="' . t('Sample search') . '">';

    $search .= '<form id="moonrock-sample-search-samples-form">';
    $search .= '<table class="moonrock-sample-search-table">';


    $search .= '<tr>';
    $search .= '<td>';
    $search .= '<label for="moonrock-sample-search-samples-location">' . t("Location: ") . '</label>';
    $search .= '</td><td>';
    $search .= '<input type="text" id="moonrock-sample-search-samples-location" name="location" />';
    $search .= '</td>';
    $search .= '</tr>';

    $search .= '</table>';
    $search .= '</form>';

    $search .= '<div style="text-align: center;">';
    $search .= '<button id="moonrock-sample-search-samples-search">' . t('Search') . '</button>';
    $search .= '<button id="moonrock-sample-search-samples-cancel">' . t('Close') . '</button>';
    $search .= '</div>';
    $search .= '</div>';

    $output .= "<div class='search-tooltip-line'>";
    $output .= "<div class='search-tooltip-element'>" . t("Sample search") . "</div>";
    $output .= "<div id='moonrock-sample-search-samples' class='search-tooltip-element search-tooltip-link search-tooltip-link-search search-tooltip-link-active'>$search</div>";
    $output .= "<div id='moonrock-sample-search-samples-clear' class='search-tooltip-element search-tooltip-link search-tooltip-link-clear'></div>";
    $output .= '<div id="moonrock-sample-search-samples-throbber" class="search-tooltip-element"></div>';
    $output .= '</div>';

    $select = $select_mode & MOONROCK_SEARCH_SAMPLE ? 'true' : 'false';
    $output .= "<div id='moonrock-sample-search-samples-results' select='{$select}'></div>";
  }

  if ($select_mode & MOONROCK_SEARCH_SNAPSHOT) {
    $output .= "<div><b>" . t("Select a snapshot:") . "</b>"
            . moonrock_sample_utils_add_info_tooltip('Sample snapshot', '<p>This measure complements Rock sample. A Sample snapshot is a close-up view of the precise point in a Rock sample where you found your data.</p>'
                    . '<p>This is useful when you want to review your data, and to provide prove of your data. When you collect new data, don\'t forget to select the right snapshot!</p>'
                    . '<p>You can only select your own snapshots. To create new snapshots, open a microscope for a sample, center the view on an interesting feature of the sample, and click on the <b>New snapshot</b> button.</p>')
            . "</div>";
  }

  if ($snapshot_search) {
    $headers = array();
    $cells = array();
    $hidden = '';

    $hidden .= '<input type="hidden" id="moonrock-sample-search-snapshots-samplerefs" name="samplerefs" />';

    if ($main_samples) {
      $headers[] = t('Snapshots of samples: ');
      $hidden .= '<input id="moonrock-sample-search-snapshots-usesamplerefs" type="hidden" name="usesamplerefs" value="1" />';
      $cell = '';

      if ($sample_search) {
        $cell .= '<input type="checkbox" name="useanysampleref" value="any" '
                . "id='moonrock-sample-search-snapshots-usesamplerefs' />"
                . "<label for='moonrock-sample-search-snapshots-usesamplerefs'>" . t('Any') . "</label><br/>";
      }
      foreach ($main_samples as $sample) {
        $id = "moonrock-sample-search-snapshots-main-samples-{$sample->nid}";
        $cell .= '<input type="checkbox" name="usemainsample" '
                . "id='$id' value='{$sample->nid}' checked='checked'/>"
                . "<label for='$id'>{$sample->title}</label><br/>";
      }

      $cells[] = $cell;
    } else if ($sample_search) {
      $headers[] = t('Snapshots of samples: ');
      $cell = '<select id="moonrock-sample-search-snapshots-usesamplerefs" name="usesamplerefs">'
              . '<option value="1">' . t('Shown samples') . '</option>'
              . '<option value="0">' . t('Any sample') . '</option>'
              . '</select>';
      $cells[] = $cell;
    } else {
      $hidden .= '<input id="moonrock-sample-search-snapshots-usesamplerefs" type="hidden" name="usesamplerefs" value="0" />';
    }



    $headers[] = t('Snapshots created by: ');
    $cell = '<select id="moonrock-sample-search-snapshots-author" name="author">'
            . '<option value="me">' . t('Me') . '</option>'
            . '<option value="any">' . t('Anyone') . '</option>'
            . '</select>';
    $cells[] = $cell;

    $headers[] = t('Keyword:');
    $cells[] = '<input type="text" id="moonrock-sample-search-snapshots-keyword" name="keyword" />';



    $headers[] = t('Similar view of a sample:');
    $explanation = '<p>' . t('No view has been selected.') . '</p><p>'
            . t('To filter snapshots by view:') . '</p><ul>'
            . '<li>' . t('Open a microscope for any sample or snapshot.') . '</li>'
            . '<li>' . t('Zoom to an interesting spot.') . '</li>'
            . '<li>' . t('Click on the button:') . '<div class="moonrock-sample-dlg-menu-search">'
            . '<div class="moonrock-sample-dlg-menu-item-buttom"></div><div style="font-size: smaller; font-weight: bold; color:gray;" class="moonrock-sample-dlg-menu-item-label">'
            . t('Search snapshots of this view') . '</div></div>'
            . '</li></ul>';

    $cell = '<div class="moonrock-sample-search-snapshots-view-tab" id="moonrock-sample-search-snapshots-view-noview">'
            . $explanation
            . '</div>'
            . '<div class="moonrock-sample-search-snapshots-view-tab" id="moonrock-sample-search-snapshots-view-view">'
            . '  <div style="width:150px;">'
            . '    <img id="moonrock-sample-search-snapshots-view-img" style="width:100%;" />'
            . '    <div style="width: 100%; text-align: center;">'
            . '      <div id="moonrock-sample-search-snapshots-view-sample" style="display: inline-block;padding-left:10px;"></div><div class="item-browser-item-title-open"></div>'
            . '    </div>'
            . '  </div>'
            . '<div><p>'
            . t('With ') . '<select id="moonrock-sample-search-snapshots-view-zoom" name="viewzoom">'
            . '<option value="0">' . t('same zoom') . '</option>'
            . '<option value="1">' . t('similar zoom') . '</option>'
            . '<option value="2">' . t('any zoom') . '</option>'
            . '</select>'
            . t(' and ') . '<select id="moonrock-sample-search-snapshots-view-position" name="viewposition">'
            . '<option value="0">' . t('same position') . '</option>'
            . '<option value="1">' . t('similar positions') . '</option>'
            . '<option value="2">' . t('any position') . '</option>'
            . '</select>'
            . '</p></div>'
            . '<div><button type="button" id="moonrock-sample-search-snapshots-view-clear">' . t('Remove view filter') . '</button></div>'
            . '</div>';
    $cells[] = $cell;
    $hidden .= '<input type="hidden" id="moonrock-sample-search-snapshots-useviewsample" name="useviewsample" />';
    $hidden .= '<input type="hidden" id="moonrock-sample-search-snapshots-useviewparameters" name="useviewparameters" />';



    $search = '<div class="moonrock-sample-search-dlg" id="moonrock-sample-search-snapshots-dlg" title="' . t('Snapshot search') . '">'
            . '<form class="moonrock-sample-search-form" id="moonrock-sample-search-snapshots-form">'
            . $hidden
            . '<table class="moonrock-sample-search-table">'
            . '<tr>';

    foreach ($headers as $header) {
      $search .= "<th>$header</th>";
    }
    $search .= '</tr><tr>';
    foreach ($cells as $cell) {
      $search .= "<td>$cell</td>";
    }

    $search .= '</tr>'
            . '</table>'
            . '</form>'
            . '<div style="text-align: center;">'
            . '<button id="moonrock-sample-search-snapshots-search">' . t('Search') . '</button>'
            . '<button id="moonrock-sample-search-snapshots-cancel">' . t('Close') . '</button>'
            . '</div>'
            . '</div>';


    $output .= "<div class='search-tooltip-line'>";
    $output .= "<div class='search-tooltip-element'>" . t("Snapshot search") . "</div>";
    $output .= "<div id='moonrock-sample-search-snapshots' class='search-tooltip-element search-tooltip-link search-tooltip-link-search search-tooltip-link-active'>$search</div>";
    $output .= "<div id='moonrock-sample-search-snapshots-clear' class='search-tooltip-element search-tooltip-link search-tooltip-link-clear'></div>";
    $output .= '<div id="moonrock-sample-search-snapshots-throbber" class="search-tooltip-element"></div>';
    $output .= '</div>';

    $select = $select_mode & MOONROCK_SEARCH_SNAPSHOT ? 'true' : 'false';
    $output .= "<div id='moonrock-sample-search-snapshots-results' select='{$select}'></div>";
  }

  if ($link_vm) {
    $output .= "<div id='moonrock-sample-newsnapshot-dlg'>" . drupal_get_form('moonrock_snapshot_form') . "</div>";
  }

  return $output;
}

/**
 * 
 * @param type $link_vm
 * @param type $sample_search
 * @param type $snapshot_search
 * @param type $select_mode
 */
function moonrock_sample_utils_load_resources($link_vm, $sample_search, $snapshot_search, $select_mode) {
  /* drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/itemBrowser.js');
    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/MoonrockSampleView.js');
    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/MoonrockSampleDialog.js');
    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/MoonrockSampleSearch.js');
    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/MoonrockSampleSelection.js');

    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/vmManager.js');

    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/dlg/vm-dlg.js');
    drupal_add_css(drupal_get_path('module', 'moonrock_sample_utils') . '/dlg/vm-dlg.css');

    drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/js/init.js');
    drupal_add_css(drupal_get_path('module', 'moonrock_sample_utils') . '/css/moonrock_sample_view.css');
    drupal_add_css(drupal_get_path('module', 'moonrock_sample_utils') . '/css/moonrock_sample_dialog.css');
    drupal_add_css(drupal_get_path('module', 'moonrock_sample_utils') . '/css/moonrock_sample_metadata.css'); */

  //drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/lib/qtip/jquery.qtip-1.0.0-rc3.js');

  jquery_ui_add("ui.dialog");
  jquery_ui_add("ui.resizable");
  jquery_ui_add("ui.draggable");
  drupal_add_css(drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/jquery-ui.css');
  drupal_add_css(drupal_get_path('module', 'jquery_ui') . '/jquery.ui/themes/base/ui.dialog.css');
  drupal_add_js(drupal_get_path('module', 'moonrock_sample_utils') . '/lib/extend-dialog/jquery.dialogextend.js');

  return;
}

function moonrock_sample_utils_prepare_object($nid) {
  global $user;

  $object = node_load($nid, NULL, TRUE);
  if ($object->type == 'moonrock_sample') {
    $sample = $object;
    $snapshot = FALSE;
  } else {
    $snapshot = $object;
    $sample = node_load($snapshot->sample_ref);
  }

  $output = array(
      "id" => $snapshot ? $snapshot->nid : $sample->nid,
      "title" => $snapshot ? $snapshot->title : $sample->title,
      "sample" => $sample->nid,
      "sample_title" => $sample->title,
      "sample_img" => moonrock_snapshot_images_get_sample_url($sample->nid),
      "snapshot" => $snapshot ? $snapshot->nid : 0,
      "snapshot_title" => $snapshot ? $snapshot->title : 0,
      "snapshot_img" => $snapshot ? moonrock_snapshot_images_get_snapshot_url($snapshot->nid) : 0,
      "own_snapshot" => $snapshot->uid === $user->uid,
      "img" => $snapshot ? moonrock_snapshot_images_get_snapshot_url($snapshot->nid) : moonrock_snapshot_images_get_sample_url($sample->nid),
      "vm" => $sample->vm,
      "type" => $object->type,
      "metadata" => array(),
  );

  if ($snapshot) {
    if ($user->uid == $snapshot->uid) {
      $author = t("Me");
    } else {
      $author_user = user_load($snapshot->uid);
      $author = check_plain($author_user->name);
    }
    $output['metadata']['author'] = array(
        "title" => t("Created by: "),
        "value" => $author,
    );
    $output['metadata']['notes'] = array(
        "title" => t("Notes: "),
        "value" => $snapshot->notes,
    );
    $output['metadata']['date'] = array(
        "title" => t("Creation date: "),
        "value" => format_date($snapshot->created, 'small'),
    );
  }

  $output['metadata']['location'] = array(
      "title" => t("Location: "),
      "value" => $sample->location . ' <a href="' . $sample->map_url . '" target="_blank" class="external_link"><div></div></a>',
  );
  $output['metadata']['source'] = array(
      "title" => t("Sample source: "),
      "value" => $sample->source,
  );

  return $output;
}

function moonrock_sample_utils_format_html_data($nid) {
  $node = node_load($nid);
  if ($node->type === 'moonrock_snapshot') {
    $img = moonrock_snapshot_images_get_snapshot_url($nid);
  } else {
    $img = moonrock_snapshot_images_get_sample_url($nid);
  }

  $title = check_plain($node->title);

  return "<img style='width: 50px' src='$img'></img><span style='padding-left: 10px;'>$title</span>";
}
