<?php



function _moonrock_sample_utils_sample_dialog_button($buttonClassSufix, $label) {
  return "<div class='moonrock-sample-dlg-menu-item moonrock-sample-dlg-menu-$buttonClassSufix'>"
          . "<div class='moonrock-sample-dlg-menu-item-buttom'></div><div class='moonrock-sample-dlg-menu-item-label'>$label</div></div>";
}


function moonrock_sample_utils_find_unique_seesamples_activity() {
  global $user;
  $node_details = get_inquiry_details_from_current_path();
  $sample_view_nid = find_unique_node_type_for_uid_and_inquiry('moonrock_seesamples', $user->uid, $node_details->inquiry_id);
  if ($sample_view_nid) {
    module_load_include('inc', 'moonrock_seesamples', 'moonrock_seesamples.table');
    return node_load($sample_view_nid);
  } else {
    return FALSE;
  }
}


function moonrock_sample_utils_add_info_tooltip($title, $content) {
  $output = "<span class='qtip-link'>"
          . "<div class='qtip-header'>$title</div>"
          . "<div class='qtip-tooltip'>$content</div>"
          . "<div class='item-browser-item-title-cluetip'></div>"
          . "</span>";

  return $output;
}

function moonrock_sample_utils_prepare_object($nid) {
  global $user;

  $object = node_load($nid, NULL, TRUE);
  if ($object->type == 'moonrock_sample') {
    $sample = $object;
    $snapshot = FALSE;
  } else {
    $snapshot = $object;
    $sample = node_load($snapshot->sample_ref);
  }

  $output = array(
      "id" => $snapshot ? $snapshot->nid : $sample->nid,
      "title" => $snapshot ? $snapshot->title : $sample->title,
      "sample" => $sample->nid,
      "sample_title" => $sample->title,
      "sample_img" => moonrock_snapshot_images_get_sample_url($sample->nid),
      "snapshot" => $snapshot ? $snapshot->nid : 0,
      "snapshot_title" => $snapshot ? $snapshot->title : 0,
      "snapshot_img" => $snapshot ? moonrock_snapshot_images_get_snapshot_url($snapshot->nid) : 0,
      "own_snapshot" => $snapshot->uid === $user->uid,
      "img" => $snapshot ? moonrock_snapshot_images_get_snapshot_url($snapshot->nid) : moonrock_snapshot_images_get_sample_url($sample->nid),
      "vm" => $sample->vm,
      "type" => $object->type,
      "metadata" => array(),
  );

  if ($snapshot) {
    if ($user->uid == $snapshot->uid) {
      $author = t("Me");
    } else {
      $author_user = user_load($snapshot->uid);
      $author = check_plain($author_user->name);
    }
    $output['metadata']['author'] = array(
        "title" => t("Created by: "),
        "value" => $author,
    );
    $output['metadata']['notes'] = array(
        "title" => t("Notes: "),
        "value" => $snapshot->notes,
    );
    $output['metadata']['date'] = array(
        "title" => t("Creation date: "),
        "value" => format_date($snapshot->created, 'small'),
    );
  }

  $output['metadata']['location'] = array(
      "title" => t("Location: "),
      "value" => $sample->location . ' <a href="' . $sample->map_url . '" target="_blank" class="external_link"><div></div></a>',
  );
  $output['metadata']['source'] = array(
      "title" => t("Sample source: "),
      "value" => $sample->source,
  );

  return $output;
}

function moonrock_sample_utils_format_html_data($nid) {
  $node = node_load($nid);
  if ($node->type === 'moonrock_snapshot') {
    $img = moonrock_snapshot_images_get_snapshot_url($nid);
  } else {
    $img = moonrock_snapshot_images_get_sample_url($nid);
  }

  $title = check_plain($node->title);

  return "<img style='width: 50px' src='$img'></img><span style='padding-left: 10px;'>$title</span>";
}
