<?php

function moonrock_vm_state_menu() {
  $items = array();

  $items['moonrock_vm_state/get'] = array(
      'page callback' => 'moonrock_vm_state_get',
      'access callback' => 'moonrock_vm_state_access',
      'type' => MENU_CALLBACK,
  );

  $items['moonrock_vm_state/set'] = array(
      'page callback' => 'moonrock_vm_state_set',
      'access callback' => 'moonrock_vm_state_access',
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function moonrock_vm_state_access() {
  return TRUE;
}

function moonrock_vm_state_set() {
  global $user;
  $sample_nid = $_REQUEST['sample_nid'];
  $image = $_REQUEST['image'];
  $position = $_REQUEST['position'];
  $view_url = $_REQUEST['viewurl'];
  
  $exists = FALSE;
  $select_query = "SELECT sample_nid FROM {moonrock_vm_state} WHERE uid='%d' AND sample_nid='%d'";
  $result = db_query($select_query, $user->uid, $sample_nid);
  if (db_fetch_object($result)) {
    $exists = TRUE;
  }
  
  if ($exists) {
    $update_query = "UPDATE {moonrock_vm_state} SET position='%s', url='%s', image='%s' WHERE uid='%d' AND sample_nid='%d'";
    db_query($update_query, $position, $view_url, $image, $user->uid, $sample_nid);
  } else {
    $insert_query = "INSERT INTO {moonrock_vm_state} (uid, sample_nid, position, url, image) values ('%d', '%d', '%s', '%s', '%s')";
    db_query($insert_query, $user->uid, $sample_nid, $position, $view_url, $image);
  }
}

function moonrock_vm_state_get() {
  global $user;
  $query = "SELECT sample_nid, position, url, image FROM {moonrock_vm_state} WHERE uid='%d'";
  $result = db_query($query, $user->uid);
  $data = array();
  while ($obj = db_fetch_object($result)) {
    $data[$obj->sample_nid] = array(
        'position' => $obj->position,
        'image' => $obj->image,
        'viewurl' => $obj->url,
    );
  }

  $ouptut = array(
      "status" => TRUE,
      "data" => $data,
  );
  drupal_json($ouptut);
}

function moonrock_vm_state_load_resources() {
   drupal_add_js(drupal_get_path('module', 'moonrock_vm_state') . '/js/MoonrockVmState.js');
}