<?php

function moonrock_snapshot_images_menu() {
  $items = array();

  $items['moonrock_snapshot_images'] = array(
      'page callback' => 'moonrock_snapshot_images_newsnapshot_transfer',
      'access callback' => 'moonrock_snapshot_images_access',
      'type' => MENU_CALLBACK,
  );
  return $items;
}

function moonrock_snapshot_images_access() {
  return true;
}

/*function moonrock_snapshot_images_newsnapshot_transfer($type, $nid) {
  $file = _moonrock_snapshot_images_filename($type, $nid);
//  $im = imagecreatefrompng();
  header('Content-Type: image/png');
  header('Content-Length: ' . filesize($file));
  echo file_get_contents($file);
//imagepng($im);
  //imagedestroy($im);
}*/

function moonrock_snapshot_images_savesnapshot($uri, $nid) {
  $parts = explode('|', $uri);
  $types = array('png', 'svg');
  
  for($i = 0; $i < 2; $i ++) {
    $data = substr($parts[$i], strpos($parts[$i], ",") + 1);
    file_put_contents(_moonrock_snapshot_images_filename($types[$i], $nid), base64_decode($data));
  }
}

function moonrock_snapshot_images_get_snapshot_url($nid) {
  return _moonrock_snapshot_images_path('png', $nid);
}
function moonrock_snapshot_images_get_svgsnapshot_url($nid) {
  return _moonrock_snapshot_images_path('svg', $nid);
}

function _moonrock_snapshot_images_path($type, $nid) {
  return "moonrock_snapshots/snapshot_{$nid}.{$type}";
}

function _moonrock_snapshot_images_filename($type, $nid) {
  return _moonrock_snapshot_images_systempath() . "snapshot_{$nid}.{$type}";
}

function _moonrock_snapshot_images_systempath() {
  $p = strrpos($_SERVER['SCRIPT_FILENAME'], '/', -1);
//  return substr($_SERVER['SCRIPT_FILENAME'], 0, $p) . '/' . file_directory_path() . '/moonrock_snapshots/';
  return substr($_SERVER['SCRIPT_FILENAME'], 0, $p) . '/moonrock_snapshots/';
}